### ISSUE TITLE
Short Positions Closing As If They Were Longs

### ISSUE THREAD

**Issue by TheRealAz** [CryptoGnome/Bybit-Futures-Bot#1]
When Taking a short position the bot will always sell at a positive % over your short causing a % loss.  Rather then closing below the Short.

Short Position:
https://media.discordapp.net/attachments/398147236610965504/887086789356032061/Capture.PNG?width=932&height=126

Take Profit:
https://media.discordapp.net/attachments/398147236610965504/887087477129625640/Capture.PNG?width=932&height=86

**Comment by CryptoGnome** [comment]
patched
