### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Jordan-Hall** [CryptoGnome/Bybit-Futures-Bot#6]
@CryptoGnome  how long until you have some documentation done. I'm trying to figure out the settings configuration.

`At Max Size for  SOL  Tier or Not Outside Drawdown Settings..`
`Does not Meet VWAP or Size Requirements`

**Comment by CryptoGnome** [comment]
I have been very busy, I do plan to do this in the future though.

**Comment by auwebsites** [comment]
Thanks Gnome.

**Comment by CryptoGnome** [comment]
Took a while but it's now done :)
https://cryptognome.gitbook.io/bybit-futures-bot/
