### ISSUE TITLE
File Not Found (setting.json)

### ISSUE THREAD

**Issue by woodylin89** [CryptoGnome/Bybit-Futures-Bot#8]
I already have downloaded settings.json why filenot found ? 

PS C:\Users\User> & C:/Users/User/AppData/Local/Programs/Python/Python36/python.exe c:/Users/User/Desktop/Bybit-Futures-Bot-main/BybitUSDT/websocket.py
Traceback (most recent call last):
  File "c:/Users/User/Desktop/Bybit-Futures-Bot-main/BybitUSDT/websocket.py", line 13, in <module>
    with open('../settings.json', 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '../settings.json'

**Comment by CryptoGnome** [comment]
make sure it is in the correct directory
